CHARACTER_NAMES = [
    # (json file, ...aliases)
    ('akuma', 'aku', 'gouki'),
    ('alisa', 'als'),
    ('anna'),
    ('armor_king', 'armorking', 'amk', 'ak'),
    ('asuka', 'asu'),
    ('bob'),
    ('bryan', 'bry'),
    ('claudio', 'cld'),
    ('devil_jin', 'deviljin', 'dvj'),
    ('dragunov', 'drag', 'sergei'),
    ('eddy'),
    ('eliza', 'elz'),
    ('feng'),
    ('geese', 'goose'),
    ('gigas', 'ggs'),
    ('heihachi', 'hei'),
    ('hwoarang', 'hwo'),  # 'whore'),
    ('jack7', 'jack-7', 'jack'),
    ('jin'),
    ('josie', 'jos'),
    ('julia', 'jul'),
    ('katarina', 'kat'),
    ('kazumi', 'kzm'),
    ('kazuya', 'kaz'),
    ('king'),
    ('kuma', 'panda'),
    ('lars'),
    ('law'),
    ('lee'),
    ('lei'),
    ('leo'),
    ('lili'),
    ('lucky_chloe', 'luckychloe', 'lck', 'lc'),
    ('marduk', 'mdk'),
    ('master_raven', 'masterraven', 'mraven', 'mrv'),
    ('miguel', 'mig'),
    ('negan', 'ngn'),
    ('nina'),
    ('noctis', 'noctu', 'noct'),
    ('paul'),
    ('shaheen', 'sha'),
    ('steve', 'stv'),
    ('yoshimitsu', 'yoshi', 'manji'),
    ('xiaoyu', 'ling'),
    ('zafina', 'zaffy', 'zaf')
]