CHARACTER_ALIAS = {
    'akuma': ['aku', 'gouki'],
    'alisa': ['als'],
    'anna': [],
    'armor_king': ['armorking', 'amk', 'ak'],
    'asuka': ['asu'],
    'bob': [],
    'bryan': ['bry'],
    'claudio': ['cld'],
    'devil_jin': ['dj', 'deviljin', 'dvj'],
    'dragunov': ['drag', 'sergei', 'dragu'],
    'eddy': [],
    'eliza': ['elz'],
    'feng': [],
    'geese': ['goose'],
    'gigas': ['ggs'],
    'heihachi': ['hei', 'hessu'],
    'hwoarang': ['hwo'],  # 'whore'],
    'jack7': ['jack-7', 'jack'],
    'jin': [],
    'josie': ['jos'],
    'julia': ['jul'],
    'katarina': ['kat'],
    'kazumi': ['kzm'],
    'kazuya': ['kaz', 'kazze', 'masku'],
    'king': [],
    'kuma': ['panda', 'karhu'],
    'lars': [],
    'law': [],
    'lee': ['violet']
    'lei': [],
    'leo': [],
    'lili': [],
    'lucky_chloe': ['luckychloe', 'lck', 'lc', 'chloe'],
    'marduk': ['mdk'],
    'master_raven': ['masterraven', 'mraven', 'mrv', 'raven'],
    'miguel': ['mig'],
    'negan': ['ngn'],
    'nina': [],
    'noctis': ['noctu', 'noct'],
    'paul': [],
    'shaheen': ['sha'],
    'steve': ['stv'],
    'yoshimitsu': ['yoshi', 'manji', 'yos'],
    'xiaoyu': ['ling'],
    'zafina': ['zaffy', 'zaf']
}

# Dict for searching special move types
MOVE_TYPES = {
    'ra': 'Rage art',
    'rage_art': 'Rage art',
    'rd': 'Rage drive',
    'rage_drive': 'Rage drive',
    'wb': 'Wall bounce',
    'wall_bounce': 'Wall bounce',
    'ts': 'Tail spin',
    'tail_spin': 'Tail spin',
    'screw': 'Tail spin',
    'homing': 'Homing',
    'homari': 'Homing',
    'armor': 'Power crush',
    'armori': 'Power crush',
    'pc': 'Power crush',
    'power': 'Power crush',
    'power_crush': 'Power crush'
}
