CHARACTER_ALIAS = {
    "armor_king": ["ak"],
    "devil_jin": ["dj", "dvj", "djin", "devil", "deviljin"],
    "dragunov": ["sergei", "drag", "dragu"],
    "geese": ["goose"],
    "heihachi": ["hei", "hessu", "heiska"],
    "hwoarang": ["hwo", "hwoa"],
    "jack": ["jack", "jack-7"],
    "katarina": ["kata", "kat"],
    "kazuya": ["kaz", "kazze"],
    "kuma": ["panda", "karhu", "bear"],
    "lucky_chloe": ["chloe", "lc", "lucky"],
    "master_raven": ["master", "raven", "mraven", "maven", "masterraven"],
    "shaheen": ["sha"],
    "yoshimitsu": ["yoshi"],
    "zafina": ["zaffy", "zaf"]
}

# Dict for searching special move types
MOVE_TYPES = {'ra': 'Rage art',
              'rage_art': 'Rage art',
              'rd': 'Rage drive',
              'rage_drive': 'Rage drive',
              'wb': 'Wall bounce',
              'wall_bounce': 'Wall bounce',
              'ts': 'Tail spin',
              'tail_spin': 'Tail spin',
              'screw': 'Tail spin',
              'homing': 'Homing',
              'homari': 'Homing',
              'armor': 'Power crush',
              'armori': 'Power crush',
              'pc': 'Power crush',
              'power': 'Power crush',
              'power_crush': 'Power crush'}